name: flutter_pedometer
description: A Pedometer and Step Detection package for Android and iOS.
version: 1.0.0
homepage:

false_secrets:
  - example/**

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_pedometer
        pluginClass: FlutterPedometerPlugin
      ios:
        pluginClass: FlutterPedometerPlugin
