name: flutter_pedometer
description: A Pedometer and Step Detection package for Android and iOS.
version: 1.0.0
homepage:

false_secrets:
  - example/**

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.38.1"

dependencies:
  flutter:
    sdk: flutter
  jni: ^0.15.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  jnigen: ^0.15.0
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        pluginClass: FlutterPedometerPlugin
